### ISSUE TITLE
License of the code

### ISSUE THREAD

**Issue by jancborchardt** [SimonAlling/kurve#3]
Hey @SimonAlling – really awesome app and a perfect rendition of the old Zatacka game. :) Thank you!

Now @MorrisJobke and I want to make it possible to install as a [Nextcloud](https://nextcloud.com) app. (Maybe you already saw https://github.com/jancborchardt/kurve :) – now we are wondering what license your code is under. MIT or AGPLv3 for example would be cool.

**Comment by SimonAlling** [comment]
I haven’t decided exactly which license to use, but I’m delighted to see that you’re trying to improve on my project. Feel free to go ahead with that as described. I’ll try to pick a license soon enough.

Please note that I’m in the process of rewriting everything in TypeScript (and possibly Elm), which should result in a stable platform for further gameplay improvements. :)

**Comment by jancborchardt** [comment]
Great, thank you @SimonAlling! :)

As far as licenses go, as mentioned we recommend MIT (permissive) or AGPLv3 (if you want changes to be open sourced also).

**Comment by jancborchardt** [comment]
Stumbled upon this again because I wanted to add kurve.se to https://osgameclones.com as it’s the clone most faithful to the original. :) Did you meanwhile decide on a license to use? If you have any questions regarding licensing I’m happy to help!

**Comment by SimonAlling** [comment]
Oh, I had forgotten about this. :sweat_smile: I absolutely love the idea of having Kurve added to OSGC. I usually use the MIT license for my projects, but since this isn't a library, but a complete game, GPLv3 seems like a good choice to me. Is there any particular reason to prefer AGPLv3 for Kurve?

**Comment by jancborchardt** [comment]
@SimonAlling cool! :) Yeah, the **A**GPLv3 closes a specific loophole for web apps which exists in the GPL. Basically it allowed someone to license their hosted app as GPL but not distributing the source code (I think). More legalese info at https://en.wikipedia.org/wiki/Affero_General_Public_License

And yep, I’d agree that MIT is for libraries or tools, and AGPLv3 is best for products. :)

**Comment by SimonAlling** [comment]
I have finally added the AGPLv3 license. Thank you for pointing this out and reminding me, @jancborchardt! :)

**Comment by SimonAlling** [comment]
I'll just produce some fitting screenshots, then I'll add Kurve to OS Game Clones.

**Comment by jancborchardt** [comment]
@SimonAlling very cool stuff! Am so happy to see the (in my opinion) very best "Achtung, die Kurve!" remake is now truly open source. :slightly_smiling_face: :tada:

**Comment by SimonAlling** [comment]
[I've made a PR now.](https://github.com/opengaming/osgameclones/pull/714)

Yeah, it's at least the only clone that could be mistaken for the original as far as I know. I originally created it because we often played Kurve on family occasions etc, but it turned out to be extremely difficult to install it on macOS, and quite a hassle on Windows as well. And we always liked the original more than any of the remakes/spinoffs. So my cousin suggested that I create "a Kurve that works on all computers". I initially said it would be too much work, but I started coding anyway, and here we are. :slightly_smiling_face:
